import {createPlan} from '@/lib/plan';
import {themes} from '@/lib/bible';
import {readPlan,savePlan} from '@/db/plans';
export const dynamic='force-dynamic';
function calendar(req:Request){const url=new URL(req.url);const zone=url.searchParams.get('tz')??'UTC';try {const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=(t:string)=>parts.find(p=>p.type===t)!.value;return {year:+part('year'),today:part('year')+'-'+part('month')+'-'+part('day')};}catch{return {year:new Date().getUTCFullYear(),today:new Date().toISOString().slice(0,10)}}}
async function identity(req:Request){const existing=req.headers.get('cookie')?.match(/(?:^|;\s*)senda_owner=([a-f0-9]{64})(?:;|$)/)?.[1];const token=existing??Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));const owner=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');return {owner,cookie:'senda_owner='+token+'; Path=/; HttpOnly; SameSite=Lax; Max-Age=34560000'+(new URL(req.url).protocol==='https:'?'; Secure':'')}}
function response(value:unknown,cookie?:string,status=200){const headers:Record<string,string>={'Content-Type':'application/json','Cache-Control':'no-store'};if(cookie)headers['Set-Cookie']=cookie;return new Response(JSON.stringify(value),{status,headers})}
export async function GET(req:Request){try{const {owner,cookie}=await identity(req),{year,today}=calendar(req);return response({plan:await readPlan(owner,year),year,today},cookie)}catch{return response({error:'No pudimos recuperar tu plan. Inténtalo de nuevo; tu plan guardado no se ha cambiado.'},undefined,503)}}
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return response({error:'Solicitud no permitida.'},undefined,403);try{const text=await req.text();if(text.length>2000)return response({error:'Solicitud demasiado grande.'},undefined,413);const body=JSON.parse(text);if(!themes.some(t=>t.id===body.theme)||typeof body.extra!=='boolean')return response({error:'Selecciona un tema y las lecturas adicionales.'},undefined,400);const {owner,cookie}=await identity(req),{year,today}=calendar(req);const current=await readPlan(owner,year);if(current&&!body.replace)return response({plan:current,year,today},cookie);const seed=crypto.getRandomValues(new Uint32Array(1))[0];const plan=createPlan(year,body.theme,body.extra,seed,crypto.randomUUID());const saved=await savePlan(owner,plan,body.replace===true);return response({plan:saved,year,today},cookie)}catch{return response({error:'No pudimos guardar el plan. Inténtalo de nuevo; el anterior seguirá disponible.'},undefined,503)}}
