'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {BookOpen,ArrowUpRight,Check,Download,ChevronLeft,ChevronRight,SlidersHorizontal,CalendarDays,ShieldCheck,RotateCcw,LoaderCircle,ArrowRight,Info} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Skeleton} from '@/components/ui/skeleton';
import {themes,months,bookMap,excluded} from '@/lib/bible';
import {label,bibleUrl,stages,type Plan,type Reading} from '@/lib/plan';
const colors=['#28687d','#805477','#447850','#91662e','#397c72','#715b9c','#a66536','#596d38','#367788','#976176','#776329','#426898'];
const versions=[['RVC','Reina Valera Contemporánea'],['NTV','Nueva Traducción Viviente'],['TLAI','Traducción en Lenguaje Actual Interconfesional']];
function localDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function endpoint(){return '/api/plan?tz='+encodeURIComponent(Intl.DateTimeFormat().resolvedOptions().timeZone)}
export default function Page(){
const [theme,setTheme]=useState('faith'),[extra,setExtra]=useState(true),[plan,setPlan]=useState<Plan|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[today,setToday]=useState(''),[month,setMonth]=useState(0),[year,setYear]=useState(new Date().getFullYear()),[reading,setReading]=useState<Reading|null>(null),[pdf,setPdf]=useState(false),[size,setSize]=useState('normal'),[settings,setSettings]=useState(false),[replace,setReplace]=useState(false),[method,setMethod]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[pdfError,setPdfError]=useState('');
async function load(initial=false){try{setError('');const response=await fetch(endpoint(),{cache:'no-store'}),data=await response.json() as {plan:Plan|null;year:number;today:string;error?:string};if(!response.ok)throw Error(data.error);setPlan(data.plan);setYear(data.year);setToday(data.today);if(initial)setMonth(+data.today.slice(5,7)-1);if(data.plan){setTheme(data.plan.theme);setExtra(data.plan.extra)}}catch(e){setError(e instanceof Error?e.message:'No pudimos recuperar tu plan.')}finally{setLoading(false)}}
useEffect(()=>{load(true);const onFocus=()=>{if(localDate()!==today)load()};window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus)},[]);
useEffect(()=>{const timer=window.setInterval(()=>{if(today&&localDate()!==today)load()},60000);return()=>clearInterval(timer)},[today]);
async function generate(regenerate=false){setBusy(true);setError('');try{const response=await fetch(endpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({theme,extra,replace:regenerate})});const data=await response.json() as {plan:Plan|null;year:number;today:string;error?:string};if(!response.ok)throw Error(data.error);setPlan(data.plan);setYear(data.year);setToday(data.today);setMonth(+data.today.slice(5,7)-1);setSettings(false);setReplace(false)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el plan.')}finally{setBusy(false)}}
function goToday(){setMonth(+today.slice(5,7)-1);requestAnimationFrame(()=>requestAnimationFrame(()=>document.getElementById('day-'+today)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})))}
async function exportPdf(){if(!plan)return;setPdfBusy(true);setPdfError('');try{const {downloadPdf}=await import('@/lib/pdf');await downloadPdf(plan,size==='large');setPdf(false)}catch(e){setPdfError(e instanceof Error?e.message:'No se pudo crear el PDF.')}finally{setPdfBusy(false)}}
const themeInfo=themes.find(t=>t.id===(plan?.theme??theme))!,currentMonth=today?+today.slice(5,7)-1:0,quarter=Math.floor(currentMonth/3),monthDays=plan?.days.filter(d=>+d.date.slice(5,7)===month+1)??[],todayDay=plan?.days.find(d=>d.date===today);
function options(prefix:string){return <><label id={prefix+'-theme-label'} className="field-label">01 <span>¿En qué deseas profundizar?</span></label><Select value={theme} onValueChange={v=>setTheme(v??'faith')}><SelectTrigger className="theme-select" aria-labelledby={prefix+'-theme-label'}><SelectValue>{themes.find(t=>t.id===theme)?.name}</SelectValue></SelectTrigger><SelectContent>{themes.map(t=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select><p className="theme-hint">{themes.find(t=>t.id===theme)?.description}</p><div className="extra-row"><div><label htmlFor={prefix+'-extra'}>¿Desea incluir lecturas adicionales?</label><p>Libros Deuterocanónicos</p></div><span>{extra?'Sí':'No'}</span><Switch id={prefix+'-extra'} checked={extra} onCheckedChange={setExtra}/></div></>}
function readLink(r:Reading){return bookMap[r.book].dc?<a className="read-link" href={bibleUrl(r,'TLAI')} target="_blank" rel="noopener noreferrer" aria-label={'Leer '+label(r)+' en TLAI (abre otra pestaña)'}>Leer ahora <ArrowUpRight/></a>:<button className="read-link" onClick={()=>setReading(r)} aria-label={'Leer '+label(r)+': elegir versión'}>Leer ahora <ArrowUpRight/></button>}
return <div className="app-shell"><a href="#main" className="skip-link">Ir al contenido</a><header><a className="brand" href="/"><BookOpen/> senda<span>LECTURA BÍBLICA</span></a><div className="header-right"><span className="year-label">UN AÑO EN LA PALABRA · {year}</span>{plan&&<button className="icon-button" aria-label="Opciones de mi plan" onClick={()=>{setTheme(plan.theme);setExtra(plan.extra);setSettings(true)}}><SlidersHorizontal/></button>}</div></header>
{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>load(true)}>Volver a intentar</button></div>}
{loading?<main id="main" className="loading-state" aria-busy="true"><BookOpen/><h1>Preparando tu espacio de lectura</h1><p>Buscando tu plan guardado…</p><Skeleton className="h-16 w-full"/><Skeleton className="h-48 w-full"/></main>:!plan?<main id="main" className="setup"><section className="intro"><span className="eyebrow">TU ENCUENTRO DE CADA DÍA</span><h1>Una lectura.<br/>Un día.<br/><em>Un nuevo camino.</em></h1><p>Recorre las Escrituras durante todo el año con un plan que conecta tus lecturas alrededor de lo que quieres profundizar.</p><div className="intro-foot"><BookOpen/><span>De enero a diciembre.<br/>Un espacio para volver a la Palabra.</span></div></section><section className="setup-card"><span className="eyebrow">DISEÑA TU RECORRIDO</span><h2>Tu año, tu enfoque.</h2><p>Elige un tema. Cada día será parte de una misma búsqueda.</p>{options('setup')}<div className="plan-summary"><span><Check/> 3–5 lecturas cada día</span><span><Check/> Salmos, Proverbios y Evangelios en ciclos</span><span><Check/> Tu plan guardado para regresar</span></div><button className="primary" disabled={busy||!!error} onClick={()=>generate()}>{busy?'Creando y guardando…':'Crear mi plan de '+year}{busy?<LoaderCircle className="spin"/>:<ArrowUpRight/>}</button><p className="small">Se guarda para este navegador, sin crear una cuenta.</p><button className="text-button method-link" onClick={()=>setMethod(true)}>Conocer el programa y sus exclusiones <Info/></button></section></main>:<main id="main" className="planner">
<div className="plan-heading"><div><span className="eyebrow">MI RECORRIDO · {year}</span><h1>Un día a la vez.</h1><p>Tu enfoque: <strong>{themeInfo.name}</strong></p></div><button className="outline-button" onClick={()=>{setPdfError('');setPdf(true)}}><Download/> Descargar trimestre</button></div>
<div className="save-note"><ShieldCheck/><span>Tu plan está guardado. Vuelve desde este navegador para continuar.</span></div>
<Tabs value={month} onValueChange={v=>setMonth(Number(v))}><div className="month-scroll"><TabsList className="month-tabs" aria-label="Meses del plan">{months.map((m,i)=><TabsTrigger value={i} key={m} className="month-tab" style={{'--month-color':colors[i]} as CSSProperties}><span className="month-dot"/>{m}</TabsTrigger>)}</TabsList></div>
<div className="reading-layout"><aside className="reading-aside"><section className="today-card"><span className="eyebrow">HOY EN TU CAMINO</span><div className="today-date">{today.slice(8)} <span>{months[currentMonth]}</span></div><p>{themes.find(t=>t.id===todayDay?.focus)?.name}</p><div className="today-refs">{todayDay?.readings.map((r,i)=><span key={i}>{label(r)}</span>)}</div><button onClick={goToday}>Ir a las lecturas de hoy <ArrowRight/></button></section><section className="rhythm"><span className="eyebrow">EL RITMO DEL AÑO</span><div><strong>02</strong><span>vueltas a Salmos<br/>y a los Evangelios</span></div><div><strong>04</strong><span>vueltas a Proverbios<br/>una cada trimestre</span></div><p><CalendarDays/> {plan.days.length} días · 3–5 lecturas al día</p></section><button className="text-button" onClick={()=>setMethod(true)}><Info/> Acerca de este recorrido</button></aside>
<TabsContent value={month} key={month} className="month-page"><div className="month-heading" style={{'--month-color':colors[month]} as CSSProperties}><div><span className="eyebrow">CAPÍTULO {String(month+1).padStart(2,'0')} DE 12</span><h2>{months[month]} <span>{year}</span></h2><p>{monthDays.length} días para volver a la Palabra</p></div><div className="month-controls"><button className="icon-button" disabled={month===0} onClick={()=>setMonth(month-1)} aria-label="Mes anterior"><ChevronLeft/></button><button className="icon-button" disabled={month===11} onClick={()=>setMonth(month+1)} aria-label="Mes siguiente"><ChevronRight/></button></div></div>
{month>=6&&<p className="chronology-note"><BookOpen/> Evangelios: segunda vuelta, por etapas de la vida y el ministerio de Jesús.</p>}
<div className="days-grid">{monthDays.map(day=><article className={'day-card '+(day.date===today?'is-today':'')} key={day.date} id={'day-'+day.date}><div className="day-top"><span className="day-number">{day.date.slice(8)}</span><div><span className="weekday">{new Date(day.date+'T12:00:00').toLocaleDateString('es',{weekday:'long'})}</span><h3>{themes.find(t=>t.id===day.focus)?.name}</h3></div>{day.date===today&&<span className="today-badge">HOY</span>}</div><ul className="readings">{day.readings.map((r,i)=><li key={i}><div><span className="reading-name">{label(r)}</span><span className="reading-meta">{bookMap[r.book].dc?'Deuterocanónico · TLAI':r.order!==undefined?stages[Math.floor(r.order/10000)]:r.book==='PSA'||r.book==='PRO'?'Vuelta '+r.cycle:bookMap[r.book].nt?'Nuevo Testamento':'Antiguo Testamento'}</span></div>{readLink(r)}</li>)}</ul><p className="connection">{day.connection}</p></article>)}</div><div className="month-bottom"><span>{months[month]} · {monthDays.reduce((n,d)=>n+d.readings.length,0)} lecturas</span>{month<11&&<button className="text-button" onClick={()=>{setMonth(month+1);document.querySelector('.month-scroll')?.scrollIntoView({block:'start',behavior:'smooth'})}}>Continuar a {months[month+1].toLowerCase()} <ArrowRight/></button>}</div></TabsContent></div></Tabs></main>}
<footer>SENDA <span>Un día a la vez.</span></footer>
<Dialog open={!!reading} onOpenChange={v=>{if(!v)setReading(null)}}><DialogContent showCloseButton={false}><BookOpen className="modal-icon"/><DialogTitle>¿En qué versión deseas leer esta lectura?</DialogTitle><DialogDescription>{reading?label(reading):''} · Elige tu traducción para abrir la lectura en YouVersion.</DialogDescription><div className="version-options">{versions.map(([id,name])=><a key={id} href={reading?bibleUrl(reading,id):'#'} target="_blank" rel="noopener noreferrer" onClick={()=>setReading(null)}><span className="version-code">{id}</span><span>{name}</span><ArrowUpRight/></a>)}</div><p className="small">Se utiliza la edición que ofrece el proveedor. En móviles compatibles el enlace puede abrir la app de YouVersion; depende de tu configuración.</p><DialogClose className="text-button">Cancelar</DialogClose></DialogContent></Dialog>
<Dialog open={pdf} onOpenChange={setPdf}><DialogContent showCloseButton={false}><Download className="modal-icon"/><DialogTitle>Tu trimestre, en papel.</DialogTitle><DialogDescription>{months[quarter*3]} a {months[quarter*3+2].toLowerCase()} de {year}. Se descarga únicamente el trimestre actual, con sus lecturas completas.</DialogDescription><RadioGroup value={size} onValueChange={v=>setSize(String(v))} aria-label="Tamaño de letra" className="font-options"><label className={size==='normal'?'selected':''}><RadioGroupItem value="normal"/><div><strong>Normal</strong><span>12 puntos · A4 · 4 páginas</span></div><span className="font-sample">Aa</span></label><label className={size==='large'?'selected':''}><RadioGroupItem value="large"/><div><strong>Grande</strong><span>18 puntos · A3 · 4 páginas</span></div><span className="font-sample large">Aa</span></label></RadioGroup><p className="small">La opción Grande utiliza papel A3 para conservar los 18 puntos. Al imprimir, elige tamaño real (100 %). El PDF usa texto seleccionable y dos tonos con contraste.</p>{pdfError&&<p role="alert" className="inline-error">{pdfError}</p>}<button className="primary" onClick={exportPdf} disabled={pdfBusy}>{pdfBusy?'Preparando PDF…':'Descargar PDF'}<Download/></button><DialogClose className="text-button">Volver al plan</DialogClose></DialogContent></Dialog>
<Dialog open={settings} onOpenChange={v=>{if(!busy)setSettings(v)}}><DialogContent showCloseButton={false}><DialogTitle>Opciones de tu plan</DialogTitle><DialogDescription>Tu recorrido actual sigue guardado. Si quieres un enfoque diferente, puedes sustituirlo por uno nuevo.</DialogDescription>{options('settings')}<button className="outline-button" onClick={()=>{setSettings(false);setReplace(true)}}><RotateCcw/> Generar un nuevo plan</button><DialogClose className="text-button">Conservar mi plan</DialogClose></DialogContent></Dialog>
<AlertDialog open={replace} onOpenChange={v=>{if(!busy)setReplace(v)}}><AlertDialogContent className="replace-dialog"><AlertDialogTitle>¿Sustituir tu plan actual?</AlertDialogTitle><AlertDialogDescription>Se generará un nuevo recorrido con el enfoque “{themes.find(t=>t.id===theme)?.name}”, {extra?'con':'sin'} lecturas deuterocanónicas. Tu plan anterior se reemplazará solo cuando el nuevo quede guardado. Los PDF ya descargados no cambiarán.</AlertDialogDescription>{error&&<p className="inline-error" role="alert">{error}</p>}<button className="primary" disabled={busy} onClick={()=>generate(true)}>{busy?'Creando y guardando…':'Sí, crear un nuevo plan'}<RotateCcw/></button><AlertDialogCancel disabled={busy}>Conservar el actual</AlertDialogCancel></AlertDialogContent></AlertDialog>
<Dialog open={method} onOpenChange={setMethod}><DialogContent className="method-dialog" showCloseButton={false}><DialogTitle>Acerca de tu recorrido</DialogTitle><DialogDescription>Un programa anual con exclusiones expresamente definidas, ciclos de lectura y un enfoque temático personal.</DialogDescription><div className="method-body"><h3>Qué se lee</h3><p>Todos los capítulos permitidos, del 1 de enero al 31 de diciembre. Salmos y Evangelios se recorren dos veces, una por semestre; Proverbios, cuatro veces, una por trimestre. Los demás capítulos aparecen una sola vez. Un mismo libro puede aparecer en varios días, con capítulos distintos.</p><h3>Cómo se relacionan</h3><p>Un índice editorial de temas por libro y capítulo prioriza tu enfoque y busca afinidades entre las lecturas diarias. Un catálogo de conexiones bíblicas refuerza los emparejamientos cuando es posible. La afinidad temática no significa que todos los pasajes se citen directamente entre sí. Para completar la cobertura, también se exploran temas complementarios.</p><h3>Los ciclos</h3><p>La primera vuelta prioriza el tema elegido. Salmos y Proverbios vuelven en secuencias aleatorias diferentes. La segunda vuelta de los Evangelios es una armonización por etapas narrativas, con algunos capítulos divididos en pasajes completos: los relatos no ofrecen un único orden histórico indiscutible para cada episodio.</p><h3>Capítulos excluidos</h3><p>{Object.entries(excluded).filter(([id])=>!bookMap[id].dc).map(([id,c])=>bookMap[id].name+' '+c).join('; ')}.</p><h3>Lecturas deuterocanónicas</h3><p>Al activarlas se añaden Tobías; Sabiduría 1–14; Eclesiástico 1–43 y 51; Baruc 1–5; la Carta de Jeremías (Baruc 6); 2 Macabeos 1–9; y las adiciones griegas de Daniel 3, 13 y 14. Judit, 1 Macabeos y Ester griego quedan excluidos por las reglas del programa. Daniel 3 habitual permanece; su adición griega se cuenta aparte. En TLAI, estas adiciones pueden aparecer como libros independientes.</p><h3>Tu plan guardado</h3><p>El plan se guarda en el servicio y una cookie privada permite recuperarlo en este navegador. Si borras las cookies, usas navegación privada u otro dispositivo, no se recuperará automáticamente. Al comenzar un nuevo año podrás crear el recorrido de ese año.</p><h3>Versiones y enlaces</h3><p>Los enlaces abren la edición disponible en YouVersion. No se atribuye a RVC una revisión 2025 o 2018 que el catálogo no identifica. No se puede elegir automáticamente cualquier app bíblica instalada.</p><div className="source-links">{versions.map(([id,name])=><a key={id} href={'https://www.bible.com/es/versions/'+({RVC:146,NTV:127,TLAI:178}[id])} target="_blank" rel="noopener noreferrer">{name} <ArrowUpRight/></a>)}</div></div><DialogClose className="outline-button">Volver a mi recorrido</DialogClose></DialogContent></Dialog>
</div>
}

